# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: 'current directory'


- script: cd azure-project && npm install 
  displayName: ’install dependencies’


- script: cd azure-project && npm build:prod 
  displayName: ‘build project‘
  





   