# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: Npm@0
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: azure-project
  
- task: Npm@0
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: npm run build --prod
    workingDir: azure-project

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Angular'
    targetPath: 'azure-project/dist'





   